[package]
name = "dayone-to-md-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4"
chrono-tz = "0.8"
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
